import axios from "axios";

// 1. The Lobby Options
export const ANIME_OPTIONS = [
  { id: "fire_force", name: "Fire Force" },
  { id: "one_piece", name: "One Piece" },
  { id: "naruto", name: "Naruto" },
  { id: "aot", name: "Attack on Titan" },
  { id: "demon_slayer", name: "Demon Slayer" },
  { id: "bleach", name: "Bleach" },
  { id: "black_clover", name: "Black Clover" },
  { id: "solo_leveling", name: "Solo Leveling" },
  { id: "jjk", name: "Jujutsu Kaisen" },
  { id: "slime", name: "TenSura (Slime)" },
  { id: "all", name: "Anime Draft (All)" },
];

// 2. The Tactical Slots
export const SLOTS = [
  { id: "captain", label: "Captain" },
  { id: "duelist", label: "Duelist" },
  { id: "tank", label: "Tank" },
  { id: "healer", label: "Support/Healer" },
  { id: "iq", label: "Tactician (IQ)" },
];

// 3. The Prime Roster (20 Characters Per Universe)
export const CHARACTERS = [
  // --- FIRE FORCE (20) ---
  {
    id: 1,
    universe: "fire_force",
    name: "Shinrabansho-Man",
    atk: 100,
    def: 90,
    spd: 100,
    tier: "S+",
    bio: "A literal god of creation who can rewrite reality.",
  },
  {
    id: 2,
    universe: "fire_force",
    name: "Arthur Boyle",
    atk: 98,
    def: 85,
    spd: 95,
    tier: "S",
    bio: "The Knight King at peak delusion, capable of cutting the Earth.",
  },
  {
    id: 3,
    universe: "fire_force",
    name: "Benimaru Shinmon",
    atk: 96,
    def: 90,
    spd: 92,
    tier: "S",
    bio: "The strongest Fire Soldier, wielding the destructive Sun Wheel.",
  },
  {
    id: 4,
    universe: "fire_force",
    name: "Haumea (Evangelist)",
    atk: 98,
    def: 95,
    spd: 90,
    tier: "S+",
    bio: "The vessel of despair who commands the collective unconscious.",
  },
  {
    id: 5,
    universe: "fire_force",
    name: "Kurono Yuichiro",
    atk: 94,
    def: 88,
    spd: 95,
    tier: "A",
    bio: "The maddest martial artist known as the 'Grim Reaper'.",
  },
  {
    id: 6,
    universe: "fire_force",
    name: "Leonard Burns",
    atk: 93,
    def: 96,
    spd: 85,
    tier: "A",
    bio: "Captain of Company 1 utilizing Voltage Nova.",
  },
  {
    id: 7,
    universe: "fire_force",
    name: "Dragon",
    atk: 97,
    def: 100,
    spd: 80,
    tier: "S",
    bio: "The invulnerable beast who seeks true despair.",
  },
  {
    id: 8,
    universe: "fire_force",
    name: "Sho Kusakabe",
    atk: 92,
    def: 85,
    spd: 98,
    tier: "A",
    bio: "Commander of the Knights capable of severing the universe's expansion.",
  },
  {
    id: 9,
    universe: "fire_force",
    name: "Charon",
    atk: 88,
    def: 99,
    spd: 80,
    tier: "A",
    bio: "A colossal tank who absorbs and reflects kinetic energy.",
  },
  {
    id: 10,
    universe: "fire_force",
    name: "Akitaru Obi",
    atk: 80,
    def: 88,
    spd: 75,
    tier: "B",
    bio: "A powerless human fighting gods with sheer willpower and gear.",
  },
  {
    id: 11,
    universe: "fire_force",
    name: "Maki Oze",
    atk: 85,
    def: 86,
    spd: 84,
    tier: "B",
    bio: "The Witch Queen who manipulates fire with incredible martial prowess.",
  },
  {
    id: 12,
    universe: "fire_force",
    name: "Tamaki Kotatsu",
    atk: 78,
    def: 82,
    spd: 88,
    tier: "B",
    bio: "A fiery nekomata who provides surprisingly versatile combat support.",
  },
  {
    id: 13,
    universe: "fire_force",
    name: "Vulcan Joseph",
    atk: 70,
    def: 75,
    spd: 70,
    tier: "C",
    bio: "Genius engineer and mechanic providing essential high-IQ tech support.",
  },
  {
    id: 14,
    universe: "fire_force",
    name: "Takehisa Hinawa",
    atk: 84,
    def: 80,
    spd: 85,
    tier: "B",
    bio: "A strict lieutenant who controls gunpowder and bullet velocity.",
  },
  {
    id: 15,
    universe: "fire_force",
    name: "Arrow",
    atk: 85,
    def: 78,
    spd: 86,
    tier: "B",
    bio: "A lethal sniper who forms a devastating fiery bow.",
  },
  {
    id: 16,
    universe: "fire_force",
    name: "Inca Kasugatani",
    atk: 88,
    def: 80,
    spd: 90,
    tier: "A",
    bio: "The Pillar of Thrills who perfectly predicts the path of flames.",
  },
  {
    id: 17,
    universe: "fire_force",
    name: "Sumire",
    atk: 90,
    def: 95,
    spd: 80,
    tier: "A",
    bio: "A terrifying pillar who can cause massive seismic quakes.",
  },
  {
    id: 18,
    universe: "fire_force",
    name: "Faerie",
    atk: 89,
    def: 85,
    spd: 92,
    tier: "A",
    bio: "A master of gravity manipulation and psychological warfare.",
  },
  {
    id: 19,
    universe: "fire_force",
    name: "Assault",
    atk: 82,
    def: 80,
    spd: 82,
    tier: "B",
    bio: "A deadly assassin specializing in explosive 'Crimson Bullet' attacks.",
  },
  {
    id: 20,
    universe: "fire_force",
    name: "Joker",
    atk: 91,
    def: 85,
    spd: 94,
    tier: "A",
    bio: "A mysterious rogue utilizing chemical-based fire and illusions.",
  },

  // --- ONE PIECE (20) ---
  {
    id: 21,
    universe: "one_piece",
    name: "Luffy (Gear 5)",
    atk: 98,
    def: 90,
    spd: 95,
    tier: "S+",
    bio: "The Sun God Nika, fighting with total freedom.",
  },
  {
    id: 22,
    universe: "one_piece",
    name: "Gol D. Roger",
    atk: 100,
    def: 95,
    spd: 95,
    tier: "S+",
    bio: "The Pirate King whose Haki conquered the seas.",
  },
  {
    id: 23,
    universe: "one_piece",
    name: "Whitebeard (Prime)",
    atk: 99,
    def: 98,
    spd: 85,
    tier: "S",
    bio: "The strongest man with the power to destroy the world.",
  },
  {
    id: 24,
    universe: "one_piece",
    name: "Zoro (King of Hell)",
    atk: 94,
    def: 88,
    spd: 90,
    tier: "A",
    bio: "Master swordsman wielding advanced Conqueror's Haki.",
  },
  {
    id: 25,
    universe: "one_piece",
    name: "Sanji (Ifrit Jambe)",
    atk: 90,
    def: 90,
    spd: 96,
    tier: "A",
    bio: "The stealthy cook utilizing genetically enhanced flaming kicks.",
  },
  {
    id: 26,
    universe: "one_piece",
    name: "Shanks",
    atk: 98,
    def: 92,
    spd: 94,
    tier: "S",
    bio: "An Emperor of the Sea with unrivaled Conqueror's Haki.",
  },
  {
    id: 27,
    universe: "one_piece",
    name: "Kaido",
    atk: 97,
    def: 99,
    spd: 88,
    tier: "S",
    bio: "The King of the Beasts, an indestructible mythic dragon.",
  },
  {
    id: 28,
    universe: "one_piece",
    name: "Big Mom",
    atk: 96,
    def: 98,
    spd: 82,
    tier: "S",
    bio: "A force of nature controlling souls, storms, and fire.",
  },
  {
    id: 29,
    universe: "one_piece",
    name: "Blackbeard",
    atk: 97,
    def: 90,
    spd: 80,
    tier: "S",
    bio: "Wields the power to nullify fruits and shatter the earth.",
  },
  {
    id: 30,
    universe: "one_piece",
    name: "Dracule Mihawk",
    atk: 97,
    def: 92,
    spd: 90,
    tier: "S",
    bio: "The World's Strongest Swordsman with the black blade Yoru.",
  },
  {
    id: 31,
    universe: "one_piece",
    name: "Akainu (Sakazuki)",
    atk: 98,
    def: 94,
    spd: 85,
    tier: "S",
    bio: "Fleet Admiral with absolute, lethal magma generation.",
  },
  {
    id: 32,
    universe: "one_piece",
    name: "Aokiji (Kuzan)",
    atk: 95,
    def: 92,
    spd: 88,
    tier: "S",
    bio: "A rogue admiral capable of freezing the ocean instantly.",
  },
  {
    id: 33,
    universe: "one_piece",
    name: "Kizaru (Borsalino)",
    atk: 92,
    def: 88,
    spd: 100,
    tier: "S",
    bio: "An admiral composed entirely of light, striking at light-speed.",
  },
  {
    id: 34,
    universe: "one_piece",
    name: "Silvers Rayleigh (Prime)",
    atk: 96,
    def: 94,
    spd: 95,
    tier: "S",
    bio: "The Dark King, Roger's unmatched right hand.",
  },
  {
    id: 35,
    universe: "one_piece",
    name: "Monkey D. Garp (Prime)",
    atk: 98,
    def: 96,
    spd: 90,
    tier: "S+",
    bio: "The Hero of the Marines who leveled mountains with his fists.",
  },
  {
    id: 36,
    universe: "one_piece",
    name: "Sengoku (Buddha)",
    atk: 95,
    def: 98,
    spd: 82,
    tier: "S",
    bio: "Former Fleet Admiral creating massive shockwaves.",
  },
  {
    id: 37,
    universe: "one_piece",
    name: "Trafalgar Law",
    atk: 92,
    def: 85,
    spd: 90,
    tier: "A",
    bio: "The Surgeon of Death, providing ultimate tactical spatial control.",
  },
  {
    id: 38,
    universe: "one_piece",
    name: "Eustass Kid",
    atk: 93,
    def: 90,
    spd: 82,
    tier: "A",
    bio: "A brutal supernova manipulating incredible magnetic forces.",
  },
  {
    id: 39,
    universe: "one_piece",
    name: "Yamato",
    atk: 92,
    def: 92,
    spd: 88,
    tier: "A",
    bio: "The mythic wolf possessing Kaido's durability and fierce Haki.",
  },
  {
    id: 40,
    universe: "one_piece",
    name: "Kozuki Oden",
    atk: 95,
    def: 90,
    spd: 88,
    tier: "S",
    bio: "A legendary samurai whose blades scarred even the toughest dragons.",
  },

  // --- NARUTO (20) ---
  {
    id: 41,
    universe: "naruto",
    name: "Naruto (Baryon Mode)",
    atk: 100,
    def: 95,
    spd: 100,
    tier: "S+",
    bio: "The ultimate life-draining fusion of chakra and power.",
  },
  {
    id: 42,
    universe: "naruto",
    name: "Isshiki Otsutsuki",
    atk: 100,
    def: 90,
    spd: 99,
    tier: "S+",
    bio: "An alien god capable of shrinking matter instantly.",
  },
  {
    id: 43,
    universe: "naruto",
    name: "Madara (Juubi)",
    atk: 98,
    def: 98,
    spd: 90,
    tier: "S",
    bio: "The Ten-Tails Jinchuriki wielding infinite Tsukuyomi.",
  },
  {
    id: 44,
    universe: "naruto",
    name: "Sasuke (Indra Susanoo)",
    atk: 97,
    def: 95,
    spd: 95,
    tier: "S",
    bio: "Wielding the Rinnegan and the chakra of all tailed beasts.",
  },
  {
    id: 45,
    universe: "naruto",
    name: "Kaguya Otsutsuki",
    atk: 99,
    def: 99,
    spd: 85,
    tier: "S",
    bio: "The progenitor of chakra who can shift dimensions.",
  },
  {
    id: 46,
    universe: "naruto",
    name: "Hashirama Senju",
    atk: 96,
    def: 95,
    spd: 88,
    tier: "S",
    bio: "The God of Shinobi and master of Wood Release.",
  },
  {
    id: 47,
    universe: "naruto",
    name: "Minato Namikaze",
    atk: 90,
    def: 80,
    spd: 100,
    tier: "A",
    bio: "The Yellow Flash of the Leaf.",
  },
  {
    id: 48,
    universe: "naruto",
    name: "Obito (Juubi)",
    atk: 96,
    def: 96,
    spd: 90,
    tier: "S",
    bio: "Wielder of Kamui and the Truth-Seeking Orbs.",
  },
  {
    id: 49,
    universe: "naruto",
    name: "Itachi Uchiha",
    atk: 94,
    def: 85,
    spd: 88,
    tier: "A",
    bio: "Genjutsu master wielding the Totsuka Blade and Yata Mirror.",
  },
  {
    id: 50,
    universe: "naruto",
    name: "Pain (Nagato)",
    atk: 95,
    def: 88,
    spd: 85,
    tier: "A",
    bio: "Leader of Akatsuki with the power of the Six Paths.",
  },
  {
    id: 51,
    universe: "naruto",
    name: "Might Guy (8th Gate)",
    atk: 99,
    def: 70,
    spd: 98,
    tier: "S",
    bio: "Taijutsu master capable of bending space with pure speed.",
  },
  {
    id: 52,
    universe: "naruto",
    name: "Kakashi (DMS)",
    atk: 95,
    def: 90,
    spd: 92,
    tier: "A",
    bio: "The Copy Ninja possessing dual Kamui and perfect Susanoo.",
  },
  {
    id: 53,
    universe: "naruto",
    name: "Jiraiya",
    atk: 88,
    def: 85,
    spd: 82,
    tier: "B",
    bio: "The Toad Sage and legendary Sannin.",
  },
  {
    id: 54,
    universe: "naruto",
    name: "Tsunade Senju",
    atk: 92,
    def: 95,
    spd: 75,
    tier: "B",
    bio: "Legendary Sannin with unmatched physical strength and healing.",
  },
  {
    id: 55,
    universe: "naruto",
    name: "Orochimaru",
    atk: 89,
    def: 92,
    spd: 85,
    tier: "A",
    bio: "Immortal Sannin possessing vast knowledge of forbidden support jutsu.",
  },
  {
    id: 56,
    universe: "naruto",
    name: "Gaara",
    atk: 85,
    def: 96,
    spd: 70,
    tier: "B",
    bio: "The Kazekage with the ultimate absolute defense of sand.",
  },
  {
    id: 57,
    universe: "naruto",
    name: "Shikamaru Nara",
    atk: 70,
    def: 75,
    spd: 75,
    tier: "B",
    bio: "A tactical genius who wins battles with his immense IQ.",
  },
  {
    id: 58,
    universe: "naruto",
    name: "Tobirama Senju",
    atk: 92,
    def: 85,
    spd: 96,
    tier: "A",
    bio: "The Second Hokage and creator of countless forbidden jutsu.",
  },
  {
    id: 59,
    universe: "naruto",
    name: "Hiruzen Sarutobi",
    atk: 88,
    def: 88,
    spd: 85,
    tier: "B",
    bio: "The Professor who mastered all nature transformations.",
  },
  {
    id: 60,
    universe: "naruto",
    name: "Momoshiki Otsutsuki",
    atk: 98,
    def: 90,
    spd: 95,
    tier: "S",
    bio: "A celestial being capable of absorbing and reflecting any jutsu.",
  },

  // --- ATTACK ON TITAN (20) ---
  {
    id: 61,
    universe: "aot",
    name: "Eren (Founding Titan)",
    atk: 99,
    def: 100,
    spd: 40,
    tier: "S+",
    bio: "Commander of the Rumbling, possessing god-like control over Eldians.",
  },
  {
    id: 62,
    universe: "aot",
    name: "Levi Ackerman",
    atk: 95,
    def: 70,
    spd: 100,
    tier: "S",
    bio: "Humanity's strongest soldier at peak physical condition.",
  },
  {
    id: 63,
    universe: "aot",
    name: "Armin (Colossal Titan)",
    atk: 95,
    def: 90,
    spd: 30,
    tier: "A",
    bio: "A tactical genius wielding the God of Destruction.",
  },
  {
    id: 64,
    universe: "aot",
    name: "Mikasa Ackerman",
    atk: 90,
    def: 75,
    spd: 92,
    tier: "A",
    bio: "A lethal protector with awakened Ackerman instincts.",
  },
  {
    id: 65,
    universe: "aot",
    name: "Zeke Yeager (Beast)",
    atk: 88,
    def: 80,
    spd: 75,
    tier: "A",
    bio: "A mastermind who weaponizes crushed stone as devastating artillery.",
  },
  {
    id: 66,
    universe: "aot",
    name: "Reiner (Armored Titan)",
    atk: 85,
    def: 98,
    spd: 65,
    tier: "A",
    bio: "The shield of Marley, possessing nearly impenetrable plating.",
  },
  {
    id: 67,
    universe: "aot",
    name: "Annie (Female Titan)",
    atk: 88,
    def: 85,
    spd: 85,
    tier: "A",
    bio: "A versatile martial artist capable of localized crystallization.",
  },
  {
    id: 68,
    universe: "aot",
    name: "Bertholdt (Colossal)",
    atk: 96,
    def: 90,
    spd: 25,
    tier: "A",
    bio: "The original God of Destruction emitting lethal steam.",
  },
  {
    id: 69,
    universe: "aot",
    name: "Erwin Smith",
    atk: 75,
    def: 70,
    spd: 70,
    tier: "B",
    bio: "The greatest commander whose IQ and leadership inspire suicide charges.",
  },
  {
    id: 70,
    universe: "aot",
    name: "Hange Zoe",
    atk: 80,
    def: 75,
    spd: 82,
    tier: "B",
    bio: "A brilliant tactician and eccentric Titan researcher.",
  },
  {
    id: 71,
    universe: "aot",
    name: "Jean Kirstein",
    atk: 78,
    def: 75,
    spd: 80,
    tier: "C",
    bio: "A highly capable and reliable leader in the Scout Regiment.",
  },
  {
    id: 72,
    universe: "aot",
    name: "Sasha Blouse",
    atk: 75,
    def: 70,
    spd: 85,
    tier: "C",
    bio: "A master marksman with extraordinary hunter instincts.",
  },
  {
    id: 73,
    universe: "aot",
    name: "Connie Springer",
    atk: 72,
    def: 70,
    spd: 86,
    tier: "C",
    bio: "A highly agile scout who excels in ODM maneuverability.",
  },
  {
    id: 74,
    universe: "aot",
    name: "Historia Reiss",
    atk: 60,
    def: 65,
    spd: 65,
    tier: "C",
    bio: "The rightful Queen of the Walls offering vital royal support.",
  },
  {
    id: 75,
    universe: "aot",
    name: "Ymir (Jaw Titan)",
    atk: 82,
    def: 75,
    spd: 90,
    tier: "B",
    bio: "A fiercely loyal combatant with a small, lightning-fast Titan form.",
  },
  {
    id: 76,
    universe: "aot",
    name: "Porco Galliard (Jaw)",
    atk: 86,
    def: 82,
    spd: 92,
    tier: "B",
    bio: "Marley's swift assault Titan with crushing bite force.",
  },
  {
    id: 77,
    universe: "aot",
    name: "Pieck Finger (Cart)",
    atk: 75,
    def: 85,
    spd: 88,
    tier: "B",
    bio: "A strategic mastermind providing extreme endurance and support.",
  },
  {
    id: 78,
    universe: "aot",
    name: "Lara Tybur (War Hammer)",
    atk: 92,
    def: 90,
    spd: 75,
    tier: "A",
    bio: "Summons devastating structural weapons from hardened Titan flesh.",
  },
  {
    id: 79,
    universe: "aot",
    name: "Grisha Yeager (Attack)",
    atk: 85,
    def: 80,
    spd: 80,
    tier: "B",
    bio: "The predecessor who stole the Founding Titan with brutal force.",
  },
  {
    id: 80,
    universe: "aot",
    name: "Ymir Fritz",
    atk: 100,
    def: 100,
    spd: 100,
    tier: "S+",
    bio: "The original progenitor with absolute power over all Titans.",
  },

  // --- DEMON SLAYER (20) ---
  {
    id: 81,
    universe: "demon_slayer",
    name: "Yoriichi Tsugikuni",
    atk: 100,
    def: 95,
    spd: 100,
    tier: "S+",
    bio: "The original Sun Breather, unmatched in human history.",
  },
  {
    id: 82,
    universe: "demon_slayer",
    name: "Muzan Kibutsuji",
    atk: 97,
    def: 99,
    spd: 95,
    tier: "S+",
    bio: "The Demon King with near-instant regeneration and lethal whips.",
  },
  {
    id: 83,
    universe: "demon_slayer",
    name: "Tanjiro (Demon King)",
    atk: 96,
    def: 98,
    spd: 88,
    tier: "S",
    bio: "The ultimate being conquering the sun itself.",
  },
  {
    id: 84,
    universe: "demon_slayer",
    name: "Kokushibo",
    atk: 98,
    def: 92,
    spd: 96,
    tier: "S",
    bio: "Upper Rank 1, wielding Moon Breathing and a flesh sword.",
  },
  {
    id: 85,
    universe: "demon_slayer",
    name: "Doma",
    atk: 94,
    def: 90,
    spd: 92,
    tier: "A",
    bio: "Upper Rank 2, a psychopathic demon manipulating deadly freezing ice.",
  },
  {
    id: 86,
    universe: "demon_slayer",
    name: "Akaza",
    atk: 92,
    def: 88,
    spd: 94,
    tier: "A",
    bio: "Upper Rank 3, a martial arts master who adapts to battle spirit.",
  },
  {
    id: 87,
    universe: "demon_slayer",
    name: "Hantengu",
    atk: 88,
    def: 95,
    spd: 85,
    tier: "B",
    bio: "Upper Rank 4, splitting into terrifying emotional manifestations.",
  },
  {
    id: 88,
    universe: "demon_slayer",
    name: "Gyokko",
    atk: 85,
    def: 88,
    spd: 82,
    tier: "B",
    bio: "Upper Rank 5, an artist of death reshaping flesh and water.",
  },
  {
    id: 89,
    universe: "demon_slayer",
    name: "Gyutaro",
    atk: 89,
    def: 80,
    spd: 90,
    tier: "B",
    bio: "Upper Rank 6, utilizing lethal blood sickles and extreme poison.",
  },
  {
    id: 90,
    universe: "demon_slayer",
    name: "Daki",
    atk: 82,
    def: 75,
    spd: 80,
    tier: "C",
    bio: "Upper Rank 6, controlling sharp, sentient Obi belts.",
  },
  {
    id: 91,
    universe: "demon_slayer",
    name: "Gyomei Himejima",
    atk: 95,
    def: 94,
    spd: 85,
    tier: "A",
    bio: "The strongest Hashira wielding a devastating spiked flail.",
  },
  {
    id: 92,
    universe: "demon_slayer",
    name: "Sanemi Shinazugawa",
    atk: 92,
    def: 85,
    spd: 92,
    tier: "A",
    bio: "The Wind Hashira with intoxicating rare blood and fierce attacks.",
  },
  {
    id: 93,
    universe: "demon_slayer",
    name: "Giyu Tomioka",
    atk: 88,
    def: 92,
    spd: 90,
    tier: "A",
    bio: "The Water Hashira with the impenetrable 'Dead Calm' defense.",
  },
  {
    id: 94,
    universe: "demon_slayer",
    name: "Obanai Iguro",
    atk: 89,
    def: 82,
    spd: 93,
    tier: "A",
    bio: "The Serpent Hashira possessing wildly unpredictable swordplay.",
  },
  {
    id: 95,
    universe: "demon_slayer",
    name: "Muichiro Tokito",
    atk: 90,
    def: 80,
    spd: 95,
    tier: "A",
    bio: "The Mist Hashira and child prodigy of obscure movement.",
  },
  {
    id: 96,
    universe: "demon_slayer",
    name: "Mitsuri Kanroji",
    atk: 86,
    def: 80,
    spd: 88,
    tier: "B",
    bio: "The Love Hashira boasting massive muscular density and flexibility.",
  },
  {
    id: 97,
    universe: "demon_slayer",
    name: "Tengen Uzui",
    atk: 88,
    def: 85,
    spd: 94,
    tier: "B",
    bio: "The Sound Hashira calculating battle via a 'Musical Score'.",
  },
  {
    id: 98,
    universe: "demon_slayer",
    name: "Kyojuro Rengoku",
    atk: 90,
    def: 85,
    spd: 89,
    tier: "A",
    bio: "The Flame Hashira with an unyielding spirit and blazing strikes.",
  },
  {
    id: 99,
    universe: "demon_slayer",
    name: "Shinobu Kocho",
    atk: 80,
    def: 70,
    spd: 96,
    tier: "B",
    bio: "The Insect Hashira acting as a master poisoner and combat medic.",
  },
  {
    id: 100,
    universe: "demon_slayer",
    name: "Zenitsu Agatsuma",
    atk: 92,
    def: 75,
    spd: 99,
    tier: "A",
    bio: "A cowardly boy who becomes a lightning-fast demon slayer while asleep.",
  },

  // --- BLEACH (20) ---
  {
    id: 101,
    universe: "bleach",
    name: "Yhwach (Soul King)",
    atk: 100,
    def: 100,
    spd: 95,
    tier: "S+",
    bio: "The Almighty who can see and alter the future.",
  },
  {
    id: 102,
    universe: "bleach",
    name: "Ichigo (True Bankai)",
    atk: 99,
    def: 90,
    spd: 98,
    tier: "S+",
    bio: "A perfect hybrid of Shinigami, Hollow, and Quincy.",
  },
  {
    id: 103,
    universe: "bleach",
    name: "Aizen (Hogyoku)",
    atk: 98,
    def: 99,
    spd: 95,
    tier: "S",
    bio: "Immortal transcended being with perfect hypnosis.",
  },
  {
    id: 104,
    universe: "bleach",
    name: "Genryusai Yamamoto",
    atk: 100,
    def: 90,
    spd: 88,
    tier: "S+",
    bio: "Head Captain whose Bankai burns as hot as the sun's core.",
  },
  {
    id: 105,
    universe: "bleach",
    name: "Ichibe Hyosube",
    atk: 97,
    def: 95,
    spd: 92,
    tier: "S",
    bio: "Leader of Squad Zero who controls all names and blackness.",
  },
  {
    id: 106,
    universe: "bleach",
    name: "Kenpachi Zaraki",
    atk: 99,
    def: 92,
    spd: 80,
    tier: "S",
    bio: "A brutal berserker whose Bankai turns him into an unstoppable demon.",
  },
  {
    id: 107,
    universe: "bleach",
    name: "Shunsui Kyoraku",
    atk: 94,
    def: 90,
    spd: 92,
    tier: "A",
    bio: "Head Captain with a terrifying reality-warping Bankai.",
  },
  {
    id: 108,
    universe: "bleach",
    name: "Kisuke Urahara",
    atk: 92,
    def: 90,
    spd: 94,
    tier: "A",
    bio: "A tactical genius whose Bankai can restructure anything it touches.",
  },
  {
    id: 109,
    universe: "bleach",
    name: "Byakuya Kuchiki",
    atk: 90,
    def: 88,
    spd: 95,
    tier: "A",
    bio: "A noble captain wielding millions of deadly cherry blossom blades.",
  },
  {
    id: 110,
    universe: "bleach",
    name: "Toshiro Hitsugaya",
    atk: 93,
    def: 85,
    spd: 90,
    tier: "A",
    bio: "A prodigy whose mature Bankai flash-freezes all matter and abilities.",
  },
  {
    id: 111,
    universe: "bleach",
    name: "Rukia Kuchiki",
    atk: 88,
    def: 80,
    spd: 85,
    tier: "B",
    bio: "Captain possessing absolute zero temperature strikes.",
  },
  {
    id: 112,
    universe: "bleach",
    name: "Renji Abarai",
    atk: 89,
    def: 85,
    spd: 82,
    tier: "B",
    bio: "A fierce fighter with a highly destructive twin-king snake Bankai.",
  },
  {
    id: 113,
    universe: "bleach",
    name: "Grimmjow Jaegerjaquez",
    atk: 88,
    def: 82,
    spd: 92,
    tier: "B",
    bio: "A vicious Espada driven entirely by predatory instinct.",
  },
  {
    id: 114,
    universe: "bleach",
    name: "Ulquiorra Cifer",
    atk: 94,
    def: 88,
    spd: 95,
    tier: "A",
    bio: "Espada 4, possessing a secret, devastating second resurrection.",
  },
  {
    id: 115,
    universe: "bleach",
    name: "Coyote Starrk",
    atk: 92,
    def: 85,
    spd: 94,
    tier: "A",
    bio: "The Primera Espada firing infinite Cero blasts.",
  },
  {
    id: 116,
    universe: "bleach",
    name: "Jugram Haschwalth",
    atk: 95,
    def: 92,
    spd: 90,
    tier: "S",
    bio: "The Sternritter Grandmaster who manipulates probability and misfortune.",
  },
  {
    id: 117,
    universe: "bleach",
    name: "Askin Nakk Le Vaar",
    atk: 90,
    def: 95,
    spd: 88,
    tier: "A",
    bio: "A lethal Quincy who calculates and controls lethal dosages.",
  },
  {
    id: 118,
    universe: "bleach",
    name: "Gerard Valkyrie",
    atk: 98,
    def: 99,
    spd: 85,
    tier: "S",
    bio: "The Miracle who revives and grows stronger from any lethal damage.",
  },
  {
    id: 119,
    universe: "bleach",
    name: "Lille Barro",
    atk: 96,
    def: 95,
    spd: 90,
    tier: "S",
    bio: "An intangible sniper whose attacks pierce everything perfectly.",
  },
  {
    id: 120,
    universe: "bleach",
    name: "Uryu Ishida",
    atk: 92,
    def: 85,
    spd: 92,
    tier: "A",
    bio: "The Antithesis, able to reverse damage between two targets.",
  },

  // --- BLACK CLOVER (20) ---
  {
    id: 121,
    universe: "black_clover",
    name: "Asta (True Devil Union)",
    atk: 98,
    def: 90,
    spd: 95,
    tier: "S",
    bio: "The ultimate anti-magic warrior capable of severing spells.",
  },
  {
    id: 122,
    universe: "black_clover",
    name: "Lucius Zogratis",
    atk: 99,
    def: 95,
    spd: 98,
    tier: "S+",
    bio: "Master of Soul, Time, and Gravity magic.",
  },
  {
    id: 123,
    universe: "black_clover",
    name: "Yuno (Star/Wind)",
    atk: 95,
    def: 88,
    spd: 99,
    tier: "A",
    bio: "Prince of the Spade Kingdom wielding dual grimoires.",
  },
  {
    id: 124,
    universe: "black_clover",
    name: "Julius Novachrono",
    atk: 97,
    def: 90,
    spd: 98,
    tier: "S",
    bio: "The Wizard King manipulating time to steal and reverse life.",
  },
  {
    id: 125,
    universe: "black_clover",
    name: "Yami Sukehiro",
    atk: 96,
    def: 88,
    spd: 90,
    tier: "A",
    bio: "Captain wielding Dark Magic that can slice through dimensions.",
  },
  {
    id: 126,
    universe: "black_clover",
    name: "Mereoleona Vermillion",
    atk: 95,
    def: 85,
    spd: 94,
    tier: "A",
    bio: "The Uncrowned Undefeated Lioness wrapped in pure mana.",
  },
  {
    id: 127,
    universe: "black_clover",
    name: "Nacht Faust",
    atk: 90,
    def: 85,
    spd: 95,
    tier: "A",
    bio: "A strategic vice-captain utilizing multiple devil shadow unions.",
  },
  {
    id: 128,
    universe: "black_clover",
    name: "Licht",
    atk: 95,
    def: 90,
    spd: 98,
    tier: "A",
    bio: "Leader of the Elves wielding Ultimate Sword Magic.",
  },
  {
    id: 129,
    universe: "black_clover",
    name: "Zagred",
    atk: 92,
    def: 88,
    spd: 90,
    tier: "A",
    bio: "A high-ranking devil wielding terrifying Word Soul Magic.",
  },
  {
    id: 130,
    universe: "black_clover",
    name: "Megicula",
    atk: 94,
    def: 92,
    spd: 85,
    tier: "S",
    bio: "The Supreme Devil of Curse-Warding Magic.",
  },
  {
    id: 131,
    universe: "black_clover",
    name: "Lucifero",
    atk: 99,
    def: 98,
    spd: 92,
    tier: "S+",
    bio: "The King of Devils whose gravity magic crushes all.",
  },
  {
    id: 132,
    universe: "black_clover",
    name: "Zenon Zogratis",
    atk: 93,
    def: 95,
    spd: 90,
    tier: "A",
    bio: "A cold executioner using Bone and Spatial Magic.",
  },
  {
    id: 133,
    universe: "black_clover",
    name: "Dante Zogratis",
    atk: 94,
    def: 96,
    spd: 88,
    tier: "A",
    bio: "An immortal dark triad utilizing Body and Gravity magic.",
  },
  {
    id: 134,
    universe: "black_clover",
    name: "Vanica Zogratis",
    atk: 92,
    def: 90,
    spd: 92,
    tier: "A",
    bio: "A manic combatant spreading Megicula's curses.",
  },
  {
    id: 135,
    universe: "black_clover",
    name: "Noelle Silva",
    atk: 90,
    def: 88,
    spd: 90,
    tier: "B",
    bio: "A royal utilizing Saint Valkyrie Armor to conquer water magic.",
  },
  {
    id: 136,
    universe: "black_clover",
    name: "Fuegoleon Vermillion",
    atk: 91,
    def: 85,
    spd: 85,
    tier: "B",
    bio: "The Crimson Lion King commanding the Fire Spirit Salamander.",
  },
  {
    id: 137,
    universe: "black_clover",
    name: "William Vangeance",
    atk: 85,
    def: 90,
    spd: 85,
    tier: "B",
    bio: "A high-IQ captain providing massive World Tree support.",
  },
  {
    id: 138,
    universe: "black_clover",
    name: "Charlotte Roselei",
    atk: 88,
    def: 85,
    spd: 88,
    tier: "B",
    bio: "Captain whose Briar Magic counters curses directly.",
  },
  {
    id: 139,
    universe: "black_clover",
    name: "Rill Boismortier",
    atk: 89,
    def: 80,
    spd: 85,
    tier: "B",
    bio: "A prodigy whose Master of Valhalla spell makes allies immortal.",
  },
  {
    id: 140,
    universe: "black_clover",
    name: "Finral Roulacase",
    atk: 70,
    def: 75,
    spd: 95,
    tier: "C",
    bio: "An incredible spatial support mage offering unmatched mobility.",
  },

  // --- SOLO LEVELING (20) ---
  {
    id: 141,
    universe: "solo_leveling",
    name: "Sung Jin-Woo (Monarch)",
    atk: 100,
    def: 99,
    spd: 100,
    tier: "S+",
    bio: "The absolute ruler of the dead.",
  },
  {
    id: 142,
    universe: "solo_leveling",
    name: "Antares",
    atk: 99,
    def: 98,
    spd: 95,
    tier: "S+",
    bio: "The Monarch of Destruction and the strongest dragon.",
  },
  {
    id: 143,
    universe: "solo_leveling",
    name: "Bellion",
    atk: 95,
    def: 95,
    spd: 90,
    tier: "S",
    bio: "The Grand Marshal of the Shadow Army.",
  },
  {
    id: 144,
    universe: "solo_leveling",
    name: "Igris",
    atk: 92,
    def: 88,
    spd: 94,
    tier: "A",
    bio: "The Blood-Red Commander and loyal swordsman.",
  },
  {
    id: 145,
    universe: "solo_leveling",
    name: "Beru",
    atk: 93,
    def: 85,
    spd: 98,
    tier: "A",
    bio: "The Shadow Ant King, a ruthless and rapid assassin.",
  },
  {
    id: 146,
    universe: "solo_leveling",
    name: "Thomas Andre",
    atk: 94,
    def: 98,
    spd: 80,
    tier: "S",
    bio: "The Goliath, a National Level Hunter with impenetrable defense.",
  },
  {
    id: 147,
    universe: "solo_leveling",
    name: "Liu Zhigang",
    atk: 95,
    def: 90,
    spd: 92,
    tier: "A",
    bio: "China's strongest National Level Hunter and dual-wielder.",
  },
  {
    id: 148,
    universe: "solo_leveling",
    name: "Christopher Reed",
    atk: 93,
    def: 88,
    spd: 88,
    tier: "A",
    bio: "A National Level Hunter embodying the spiritual body of a dragon.",
  },
  {
    id: 149,
    universe: "solo_leveling",
    name: "Hwang Dong-Su",
    atk: 85,
    def: 88,
    spd: 82,
    tier: "B",
    bio: "A brutal S-Rank hunter and physical powerhouse.",
  },
  {
    id: 150,
    universe: "solo_leveling",
    name: "Cha Hae-In",
    atk: 88,
    def: 80,
    spd: 95,
    tier: "A",
    bio: "Korea's fastest S-Rank swordswoman.",
  },
  {
    id: 151,
    universe: "solo_leveling",
    name: "Go Gun-Hee",
    atk: 92,
    def: 90,
    spd: 85,
    tier: "A",
    bio: "The Chairman and secret vessel of the Rulers.",
  },
  {
    id: 152,
    universe: "solo_leveling",
    name: "Baek Yoonho",
    atk: 85,
    def: 90,
    spd: 82,
    tier: "B",
    bio: "Guild Master possessing incredible Beast Transformation.",
  },
  {
    id: 153,
    universe: "solo_leveling",
    name: "Choi Jong-In",
    atk: 88,
    def: 75,
    spd: 80,
    tier: "B",
    bio: "The Ultimate Hunter specializing in massive fire magic.",
  },
  {
    id: 154,
    universe: "solo_leveling",
    name: "Iron",
    atk: 80,
    def: 95,
    spd: 70,
    tier: "B",
    bio: "A massive Shadow Knight specializing in heavy aggro defense.",
  },
  {
    id: 155,
    universe: "solo_leveling",
    name: "Tusk",
    atk: 89,
    def: 80,
    spd: 75,
    tier: "B",
    bio: "A Shadow High Orc firing devastating magical bombardments.",
  },
  {
    id: 156,
    universe: "solo_leveling",
    name: "Greed",
    atk: 86,
    def: 90,
    spd: 80,
    tier: "B",
    bio: "A shadow consumed by avarice and raw power.",
  },
  {
    id: 157,
    universe: "solo_leveling",
    name: "Kamish",
    atk: 96,
    def: 94,
    spd: 90,
    tier: "S",
    bio: "Humanity's greatest disaster, a dragon of pure ruin.",
  },
  {
    id: 158,
    universe: "solo_leveling",
    name: "The Architect",
    atk: 94,
    def: 90,
    spd: 88,
    tier: "S",
    bio: "Creator of the System, a multi-armed mastermind.",
  },
  {
    id: 159,
    universe: "solo_leveling",
    name: "Querehsha",
    atk: 92,
    def: 85,
    spd: 90,
    tier: "A",
    bio: "The Monarch of Plagues utilizing deadly venom.",
  },
  {
    id: 160,
    universe: "solo_leveling",
    name: "Baran",
    atk: 94,
    def: 90,
    spd: 88,
    tier: "S",
    bio: "The Monarch of White Flames and lord of demons.",
  },
  // --- JUJUTSU KAISEN (JJK) ---
  {
    id: 161,
    universe: "jjk",
    name: "Ryomen Sukuna",
    atk: 99,
    def: 95,
    spd: 92,
    tier: "S+",
    img: "/images/jjk/sukuna.jpg",
    bio: "The absolute pinnacle of Jujutsu sorcery.",
  },
  {
    id: 162,
    universe: "jjk",
    name: "Gojo Satoru",
    atk: 96,
    def: 100,
    spd: 95,
    tier: "S+",
    img: "/images/jjk/gojo.webp",
    bio: "Wielder of the Limitless and the Six Eyes.",
  },
  {
    id: 163,
    universe: "jjk",
    name: "Yuta Okkotsu",
    atk: 94,
    def: 88,
    spd: 88,
    tier: "S",
    img: "/images/jjk/yuta.jpg",
    bio: "Prodigy capable of infinite cursed energy and copy.",
  },
  {
    id: 164,
    universe: "jjk",
    name: "Kenjaku",
    atk: 90,
    def: 92,
    spd: 85,
    tier: "S",
    img: "/images/jjk/kenjaku.webp",
    bio: "An ancient mastermind wielding Curse Manipulation.",
  },
  {
    id: 165,
    universe: "jjk",
    name: "Mahoraga",
    atk: 95,
    def: 99,
    spd: 90,
    tier: "S",
    img: "/images/jjk/mahoraga.jpg",
    bio: "The divine general capable of adapting to any phenomenon.",
  },
  {
    id: 166,
    universe: "jjk",
    name: "Toji Fushiguro",
    atk: 96,
    def: 90,
    spd: 98,
    tier: "S",
    img: "/images/jjk/toji.jpg",
    bio: "The Sorcerer Killer with physical perfection.",
  },
  {
    id: 167,
    universe: "jjk",
    name: "Maki Zenin",
    atk: 95,
    def: 90,
    spd: 97,
    tier: "A",
    img: "/images/jjk/maki.webp",
    bio: "A heavenly restricted warrior matching Toji's prowess.",
  },
  {
    id: 168,
    universe: "jjk",
    name: "Kinji Hakari",
    atk: 88,
    def: 100,
    spd: 85,
    tier: "A",
    img: "/images/jjk/kinji.jpg",
    bio: "An immortal gambler riding an endless jackpot.",
  },
  {
    id: 169,
    universe: "jjk",
    name: "Hajime Kashimo",
    atk: 95,
    def: 80,
    spd: 96,
    tier: "A",
    img: "/images/jjk/hajime.png",
    bio: "God of Lightning who unleashes a mythic beast form.",
  },
  {
    id: 170,
    universe: "jjk",
    name: "Yuki Tsukumo",
    atk: 96,
    def: 85,
    spd: 88,
    tier: "A",
    img: "/images/jjk/yuki.png",
    bio: "A Special Grade adding immense virtual mass to her strikes.",
  },
  {
    id: 171,
    universe: "jjk",
    name: "Suguru Geto",
    atk: 92,
    def: 88,
    spd: 85,
    tier: "A",
    img: "/images/jjk/suguru.png",
    bio: "A Special Grade commanding thousands of cursed spirits.",
  },
  {
    id: 172,
    universe: "jjk",
    name: "Mahito",
    atk: 90,
    def: 95,
    spd: 88,
    tier: "A",
    img: "/images/jjk/mahito.jpg",
    bio: "A disaster curse rewriting the shape of human souls.",
  },
  {
    id: 173,
    universe: "jjk",
    name: "Jogo",
    atk: 92,
    def: 75,
    spd: 94,
    tier: "A",
    img: "/images/jjk/jogo.jpg",
    bio: "A highly destructive volcano curse with massive firepower.",
  },
  {
    id: 174,
    universe: "jjk",
    name: "Hanami",
    atk: 85,
    def: 94,
    spd: 80,
    tier: "B",
    img: "/images/jjk/hanami.webp",
    bio: "A durable nature curse with immense regenerative plants.",
  },
  {
    id: 175,
    universe: "jjk",
    name: "Dagon",
    atk: 82,
    def: 90,
    spd: 75,
    tier: "B",
    img: "/images/jjk/dagon.jpg",
    bio: "An ocean curse whose Domain unleashes an endless swarm.",
  },
  {
    id: 176,
    universe: "jjk",
    name: "Choso",
    atk: 88,
    def: 85,
    spd: 85,
    tier: "B",
    img: "/images/jjk/choso.jpg",
    bio: "A Death Painting Womb mastering Piercing Blood.",
  },
  {
    id: 177,
    universe: "jjk",
    name: "Yuji Itadori",
    atk: 90,
    def: 90,
    spd: 90,
    tier: "B",
    img: "/images/jjk/yuji.jpg",
    bio: "A martial arts powerhouse landing continuous Black Flashes.",
  },
  {
    id: 178,
    universe: "jjk",
    name: "Megumi Fushiguro",
    atk: 85,
    def: 82,
    spd: 85,
    tier: "B",
    img: "/images/jjk/megumi.jpg",
    bio: "Genius shadow user commanding the Ten Shadows Technique.",
  },
  {
    id: 179,
    universe: "jjk",
    name: "Nobara Kugisaki",
    atk: 80,
    def: 75,
    spd: 80,
    tier: "C",
    img: "/images/jjk/nobara.jpg",
    bio: "A fierce sorcerer utilizing lethal Resonance.",
  },
  {
    id: 180,
    universe: "jjk",
    name: "Kento Nanami",
    atk: 86,
    def: 85,
    spd: 82,
    tier: "B",
    img: "/images/jjk/kento.jpg",
    bio: "A disciplined combatant forcing critical hits at a 7:3 ratio.",
  },

  // --- TENSURA (SLIME) ---
  {
    id: 181,
    universe: "slime",
    name: "Rimuru Tempest",
    atk: 100,
    def: 100,
    spd: 99,
    tier: "S+",
    img: "/images/slime/rimuru.jpg",
    bio: "A god-like entity ruling the Jura Tempest Federation.",
  },
  {
    id: 182,
    universe: "slime",
    name: "Guy Crimson",
    atk: 98,
    def: 98,
    spd: 96,
    tier: "S+",
    img: "/images/slime/guy.jpg",
    bio: "The first and strongest of the Primordial Demons.",
  },
  {
    id: 183,
    universe: "slime",
    name: "Milim Nava",
    atk: 99,
    def: 90,
    spd: 95,
    tier: "S+",
    img: "/images/slime/milim.jpg",
    bio: "The Destroyer, possessing endless stardust energy.",
  },
  {
    id: 184,
    universe: "slime",
    name: "Veldora Tempest",
    atk: 96,
    def: 94,
    spd: 90,
    tier: "S",
    img: "/images/slime/veldora.webp",
    bio: "The Storm Dragon bringing chaotic destruction.",
  },
  {
    id: 185,
    universe: "slime",
    name: "Velzard",
    atk: 97,
    def: 96,
    spd: 92,
    tier: "S",
    img: "/images/slime/velzard.jpg",
    bio: "The White Ice Dragon who freezes the world completely.",
  },
  {
    id: 186,
    universe: "slime",
    name: "Velgrynd",
    atk: 96,
    def: 92,
    spd: 98,
    tier: "S",
    img: "/images/slime/velgrynd.jpg",
    bio: "The Scorch Dragon boasting unmatched thermal acceleration.",
  },
  {
    id: 187,
    universe: "slime",
    name: "Diablo",
    atk: 95,
    def: 90,
    spd: 95,
    tier: "A",
    img: "/images/slime/diablo.jpg",
    bio: "A mysterious Primordial Black Demon utterly loyal to Rimuru.",
  },
  {
    id: 188,
    universe: "slime",
    name: "Zegion",
    atk: 94,
    def: 95,
    spd: 92,
    tier: "A",
    img: "/images/slime/zegion.webp",
    bio: "The strongest subordinate with impenetrable illusion logic.",
  },
  {
    id: 189,
    universe: "slime",
    name: "Benimaru",
    atk: 92,
    def: 85,
    spd: 90,
    tier: "A",
    img: "/images/slime/benimaru.jpg",
    bio: "Commander-in-Chief incinerating foes with Hell Flare.",
  },
  {
    id: 190,
    universe: "slime",
    name: "Shion",
    atk: 93,
    def: 88,
    spd: 85,
    tier: "A",
    img: "/images/slime/shion.jpg",
    bio: "A ruthless warrior whose sword literally alters reality.",
  },
  {
    id: 191,
    universe: "slime",
    name: "Hakurou",
    atk: 88,
    def: 80,
    spd: 96,
    tier: "B",
    img: "/images/slime/hakurou.webp",
    bio: "An elderly master sword-demon with instantaneous strikes.",
  },
  {
    id: 192,
    universe: "slime",
    name: "Souei",
    atk: 85,
    def: 75,
    spd: 98,
    tier: "B",
    img: "/images/slime/souei.jpg",
    bio: "The shadow commander utilizing lethal threads and stealth.",
  },
  {
    id: 193,
    universe: "slime",
    name: "Ranga",
    atk: 86,
    def: 85,
    spd: 92,
    tier: "B",
    img: "/images/slime/ranga.webp",
    bio: "A massive Star Wolf summoning divine lightning storms.",
  },
  {
    id: 194,
    universe: "slime",
    name: "Gobta",
    atk: 75,
    def: 80,
    spd: 85,
    tier: "C",
    img: "/images/slime/gobta.jpg",
    bio: "A genius hobgoblin providing unpredictable tactical support.",
  },
  {
    id: 195,
    universe: "slime",
    name: "Geld",
    atk: 85,
    def: 98,
    spd: 70,
    tier: "B",
    img: "/images/slime/geld.jpg",
    bio: "The absolute shield of Tempest, an unbreakable Orc King.",
  },
  {
    id: 196,
    universe: "slime",
    name: "Gabiru",
    atk: 82,
    def: 85,
    spd: 80,
    tier: "B",
    img: "/images/slime/gabiru.jpg",
    bio: "A Dragonewt leader boosting morale with mysterious luck.",
  },
  {
    id: 197,
    universe: "slime",
    name: "Testarossa",
    atk: 93,
    def: 85,
    spd: 90,
    tier: "A",
    img: "/images/slime/testarossa.jpg",
    bio: "Primordial Blanc wielding deadly nuclear strikes.",
  },
  {
    id: 198,
    universe: "slime",
    name: "Carrera",
    atk: 95,
    def: 80,
    spd: 88,
    tier: "A",
    img: "/images/slime/carrera.jpg",
    bio: "Primordial Jaune packing extreme raw magical destruction.",
  },
  {
    id: 199,
    universe: "slime",
    name: "Ultima",
    atk: 92,
    def: 82,
    spd: 94,
    tier: "A",
    img: "/images/slime/ultima.jpg",
    bio: "Primordial Violet striking with lethal poison and speed.",
  },
  {
    id: 200,
    universe: "slime",
    name: "Ramiris",
    atk: 70,
    def: 95,
    spd: 85,
    tier: "A",
    img: "/images/slime/ramiris.jpg",
    bio: "Fairy Queen utilizing absolute labyrinth creation for support.",
  },
];

// 4. Unique Pull Logic (Respects Universe Selection)
export const getRandomUniqueByUniverse = (usedIds, universeId) => {
  let pool = CHARACTERS.filter((char) => !usedIds.includes(char.id));

  if (universeId !== "all") {
    pool = pool.filter((char) => char.universe === universeId);
  }

  return pool.length > 0 ? pool[Math.floor(Math.random() * pool.length)] : null;
};

// 5. Backend Communication
export const api = {
  fight: async (payload) => {
    // Ab hum pura payload (jisme teams array aur mode dono hain) directly bhej rahe hain
    const res = await axios.post(
      "https://anime-draft-game-1.onrender.com/api/battle",
      payload,
    );
    return res.data;
  },
};
